spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl?Unicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false
    username: hr
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

document:
  uploadPath: /src/main/resources/upload/
  imgPath: http://127.0.0.1:8081/


knife4j:
  #enable: true
  enable: false
  basic:
    #enable: true
    enable: false
    username: admin
    password: 123456
