server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl?Unicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false
    username: hr
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 3000000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat, wall, log4j
    stat-view-servlet:
      enabled: true
      login-username: admin
      login-password: 123456
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    port: 6379
    host: 127.0.0.1

document:
  uploadPath: /src/main/resources/upload/
  imgPath: http://127.0.0.1:8081/


knife4j:
  #是否开启增强模式
  enable: false
  basic:
    enable: false
    username: admin
    password: 123456

